INFO_PREFIX = 'info_'
SEX_PREFIX  = 'sex_'
OCCUPATION_PREFIX = 'occupation_'
NEW_SEX_PREFIX = 'new_sex_'
CHANGE_PREFIX = 'change_'
COLOR_PREFIX = 'color_'
INFO_PREFIX = 'info_'
ANSWER_PREFIX = 'answer_'

FIELDNAME_TIMEZONE = 'timezone'
FIELDNAME_QUESTION_TIME = 'question_time_minutes'
FIELDNAME_SEX = 'sex'
FIELDNAME_AGE = 'age'
FIELDNAME_CITY = 'city'
FIELDNAME_OCCUPATION = 'occupation'
FIELDNAME_UTC_QUESTION_TIME = 'utc_question_time_minutes'
FIELDNAME_UTC_MIDNIGHT = 'utc_midnight_time_minutes'
FIELDNAME_USER_ID = 'user_id'
FIELDNAME_ANSWER_STATUS = 'answer_status'
FIELDNAME_TEXT = 'text'
FIELDNAME_TIME = 'time'
FIELDNAME_DATE = 'date'
FIELDNAME_COLORS = 'colors'


NOTHING = 'nothing'